### ISSUE TITLE
Smash Ultimate mode not functioning

### ISSUE THREAD

**Issue by magicmanfk** [HandHeldLegend/ProCon-GCC-PIC18#4]
I am holding down the B button when plugging in the controller to a Nintendo Switch using a usb-c to gc cable, and the Switch does not recognize it at all. Holding right on the dpad works as expected without a functioning L button. I tried right on dpad + B  when booting but it did not recognize the controller. The instructions say to hold down b "while booting", does that mean something different than when plugging in?

**Comment by mitchellcairns** [comment]
If you're having issues with a kit you bought, please open a ticket with support@handheldlegend.com

This would be a place to submit issues with the code.

Here's the user guide for the v2 https://wiki.handheldlegend.com/progcc-user-guide
